# Generated by Django 4.2.6 on 2023-10-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoModules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
